name: Auto Check Lint
on:
  - pull_request
  - push

jobs: 
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - run: |
          npm ci
          npm run lint
